In [1]:
import pandas as pd

df= pd.read_csv("Amazon Sale Report.csv")
print(df.columns.tolist())

C:\Users\jayachandran\AppData\Local\Temp\ipykernel_22228\1741654846.py:3: DtypeWarning: Columns (23: Unnamed: 22) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv("Amazon Sale Report.csv")

['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ', 'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids', 'B2B', 'fulfilled-by', 'Unnamed: 22']

In [2]:
# Remove unwanted columns
df = df.loc[:, ~df.columns.str.startswith("Unnamed:")]

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Check the dataset
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

df.head()

Dataset shape: (128975, 23)

Column names:
['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel', 'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids', 'B2B', 'fulfilled-by']

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN

In [6]:
df.info()

print("\nMissing values in each column:")
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 23 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  str
 2   Date                128975 non-null  str
 3   Status              128975 non-null  str
 4   Fulfilment          128975 non-null  str
 5   Sales Channel       128975 non-null  str
 6   ship-service-level  128975 non-null  str
 7   Style               128975 non-null  str
 8   SKU                 128975 non-null  str
 9   Category            128975 non-null  str
 10  Size                128975 non-null  str
 11  ASIN                128975 non-null  str
 12  Courier Status      122103 non-null  str
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  str
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  str
 17  ship-state          128942 non-null  str
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  str
 20  promotion-ids       79822 non-null   str
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   str
dtypes: bool(1), float64(2), int64(2), str(18)
memory usage: 81.3 MB

Missing values in each column:
index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
dtype: int64

In [7]:
# Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

# Check missing values
print("\nMissing values:")
print(df.isnull().sum().sort_values(ascending=False))

# Check order statuses
print("\nOrder statuses:")
print(df["Status"].value_counts())

# Check date range
df["Date"] = pd.to_datetime(
    df["Date"], errors="coerce"
)

print("\nDate range:")
print("Start:", df["Date"].min())
print("End:", df["Date"].max())

# Check the extra index column
print("\nFirst 10 index values:")
print(df["index"].head(10).tolist())

Duplicate rows: 0

Missing values:
fulfilled-by          89698
promotion-ids         49153
currency               7795
Amount                 7795
Courier Status         6872
ship-city                33
ship-state               33
ship-country             33
ship-postal-code         33
Fulfilment                0
Sales Channel             0
Date                      0
Order ID                  0
index                     0
Status                    0
ship-service-level        0
ASIN                      0
Qty                       0
Size                      0
SKU                       0
Style                     0
Category                  0
B2B                       0
dtype: int64

Order statuses:
Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

Date range:
Start: 2022-03-31 00:00:00
End: 2022-06-29 00:00:00

First 10 index values:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

C:\Users\jayachandran\AppData\Local\Temp\ipykernel_26536\1917059285.py:13: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(

In [3]:
# Convert dates using the known format
df["Date"] = pd.to_datetime(
    df["Date"],
    format="%m-%d-%y",
    errors="coerce"
)

# Remove the redundant row-index column
df = df.drop(columns=["index"], errors="ignore")

# Remove duplicate rows, if any
df = df.drop_duplicates()

# Check the results
print("Dataset shape:", df.shape)
print("Duplicate rows:", df.duplicated().sum())
print("Missing dates:", df["Date"].isna().sum())

print("\nDate range:")
print(df["Date"].min(), "to", df["Date"].max())

Dataset shape: (128969, 22)
Duplicate rows: 0
Missing dates: 0

Date range:
2022-03-31 00:00:00 to 2022-06-29 00:00:00

In [4]:
# Check data types and missing values in key columns
key_columns = [
    "Order ID",
    "Date",
    "Status",
    "Category",
    "Qty",
    "currency",
    "Amount",
    "ship-state"
]

print(df[key_columns].isnull().sum())

print("\nQuantity data type:", df["Qty"].dtype)
print("Amount data type:", df["Amount"].dtype)

print("\nNegative quantities:", (df["Qty"] < 0).sum())
print("Zero quantities:", (df["Qty"] == 0).sum())
print("Negative amounts:", (df["Amount"] < 0).sum())

Order ID         0
Date             0
Status           0
Category         0
Qty              0
currency      7792
Amount        7792
ship-state      33
dtype: int64

Quantity data type: int64
Amount data type: float64

Negative quantities: 0
Zero quantities: 12804
Negative amounts: 0

In [5]:
#Investigate missing amounts and zero quantities
# Check quantity against order status
print("Quantity by order status:")
print(
    df.groupby("Status")["Qty"]
      .agg(["count", "sum"])
      .sort_values("count", ascending=False)
)

print("\nZero-quantity rows by status:")
print(
    df[df["Qty"] == 0]["Status"]
      .value_counts()
)

print("\nMissing amounts by status:")
print(
    df[df["Amount"].isna()]["Status"]
      .value_counts()
)

print("\nCurrency values:")
print(df["currency"].value_counts(dropna=False))

print("\nSample rows with missing amounts:")
display(
    df[df["Amount"].isna()][
        ["Order ID", "Date", "Status", "Category", "Qty", "currency", "Amount"]
    ].head(10)
)

Quantity by order status:
                               count    sum
Status
Shipped                        77801  78006
Shipped - Delivered to Buyer   28769  28886
Cancelled                      18329   5657
Shipped - Returned to Seller    1953   1970
Shipped - Picked Up              973    977
Pending                          658    657
Pending - Waiting for Pick Up    281    283
Shipped - Returning to Seller    145    150
Shipped - Out for Delivery        35     35
Shipped - Rejected by Buyer       11     11
Shipping                           8      8
Shipped - Lost in Transit          5      5
Shipped - Damaged                  1      1

Zero-quantity rows by status:
Status
Cancelled                       12698
Shipped                            93
Shipped - Delivered to Buyer        8
Shipped - Returned to Seller        3
Pending                             2
Name: count, dtype: int64

Missing amounts by status:
Status
Cancelled                       7563
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

Currency values:
currency
INR    121177
NaN      7792
Name: count, dtype: int64

Sample rows with missing amounts:

                Order ID       Date     Status Category  Qty currency  Amount
8    407-5443024-5233168 2022-04-30  Cancelled      Set    0      NaN     NaN
29   404-5933402-8801952 2022-04-30  Cancelled    kurta    0      NaN     NaN
65   171-4137548-0481151 2022-04-30  Cancelled    kurta    0      NaN     NaN
84   403-9950518-0349133 2022-04-30  Cancelled    kurta    0      NaN     NaN
95   405-9112089-3379536 2022-04-30  Cancelled    kurta    0      NaN     NaN
101  402-7841951-1872363 2022-04-30  Cancelled      Set    0      NaN     NaN
132  171-0293372-4913973 2022-04-30  Cancelled      Set    0      NaN     NaN
139  403-6442534-2769112 2022-04-30  Cancelled      Top    0      NaN     NaN
155  402-8078642-8565124 2022-04-30  Cancelled    kurta    0      NaN     NaN
165  406-0218328-1773963 2022-04-30  Cancelled    kurta    0      NaN     NaN

In [6]:
#Prepare the cleaned dataset for SQL
# Create a separate copy for the SQL database
sql_df = df.copy()

# Standardize column names for SQL and Python
sql_df.columns = (
    sql_df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"[^a-z0-9]+", "_", regex=True)
    .str.strip("_")
)

# Rename amount to make its meaning explicit
sql_df = sql_df.rename(columns={"amount": "order_value"})

# Represent missing location as Unknown
sql_df["ship_state"] = sql_df["ship_state"].fillna("Unknown")

# Verify the cleaned structure
print("Dataset shape:", sql_df.shape)
print("\nColumns:")
print(sql_df.columns.tolist())

print("\nMissing values in important fields:")
print(sql_df[["order_id", "date", "status", "qty",
              "currency", "order_value", "ship_state"]].isnull().sum())

sql_df.head()

Dataset shape: (128969, 22)

Columns:
['order_id', 'date', 'status', 'fulfilment', 'sales_channel', 'ship_service_level', 'style', 'sku', 'category', 'size', 'asin', 'courier_status', 'qty', 'currency', 'order_value', 'ship_city', 'ship_state', 'ship_postal_code', 'ship_country', 'promotion_ids', 'b2b', 'fulfilled_by']

Missing values in important fields:
order_id          0
date              0
status            0
qty               0
currency       7792
order_value    7792
ship_state        0
dtype: int64

,order_id,date,status,fulfilment,sales_channel,ship_service_level,style,sku,category,size,...,qty,currency,order_value,ship_city,ship_state,ship_postal_code,ship_country,promotion_ids,b2b,fulfilled_by
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN

In [7]:
#Creating SQLite database
import sqlite3

# Create a SQLite database file
conn = sqlite3.connect("amazon_sales.db")

# Save the cleaned dataset as a SQL table
sql_df.to_sql(
    "amazon_sales",
    conn,
    if_exists="replace",
    index=False
)

print("SQLite database created successfully!")

# Verify the table
cursor = conn.cursor()

cursor.execute("SELECT COUNT(*) FROM amazon_sales")
print("Rows in SQL table:", cursor.fetchone()[0])

cursor.execute("PRAGMA table_info(amazon_sales)")
print("\nSQL table columns:")
for column in cursor.fetchall():
    print(column[1], "-", column[2])

SQLite database created successfully!
Rows in SQL table: 128969

SQL table columns:
order_id - TEXT
date - TIMESTAMP
status - TEXT
fulfilment - TEXT
sales_channel - TEXT
ship_service_level - TEXT
style - TEXT
sku - TEXT
category - TEXT
size - TEXT
asin - TEXT
courier_status - TEXT
qty - INTEGER
currency - TEXT
order_value - REAL
ship_city - TEXT
ship_state - TEXT
ship_postal_code - REAL
ship_country - TEXT
promotion_ids - TEXT
b2b - INTEGER
fulfilled_by - TEXT

In [8]:
query = """
SELECT
    category,
    COUNT(*) AS total_rows,
    SUM(qty) AS total_quantity,
    ROUND(SUM(order_value), 2) AS total_order_value
FROM amazon_sales
WHERE status != 'Cancelled'
  AND order_value IS NOT NULL
GROUP BY category
ORDER BY total_order_value DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)

display(result)

        category  total_rows  total_quantity  total_order_value
0            Set       42841           42968         35729571.0
1          kurta       42521           42716         19425337.0
2  Western Dress       13369           13414         10209590.0
3            Top        9336            9364          4904066.0
4   Ethnic Dress        1013            1016           732744.0
5         Blouse         806             812           418389.0
6         Bottom         379             383           135453.0
7          Saree         143             147           114694.0
8        Dupatta           3               3              915.0

In [9]:
#Verify the database
print("Database connection:", conn.execute("SELECT 1").fetchone())
print("Total rows:", conn.execute(
    "SELECT COUNT(*) FROM amazon_sales"
).fetchone()[0])
print("Unique order IDs:", conn.execute(
    "SELECT COUNT(DISTINCT order_id) FROM amazon_sales"
).fetchone()[0])

Database connection: (1,)
Total rows: 128969
Unique order IDs: 120378

In [15]:
%pip install -U langchain langchain-community langchain-ollama sqlalchemy

Collecting langchain
  Downloading langchain-1.4.4-py3-none-any.whl.metadata (6.2 kB)
Collecting langchain-community
  Downloading langchain_community-0.4.2-py3-none-any.whl.metadata (3.4 kB)
Collecting langchain-ollama
  Downloading langchain_ollama-1.1.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: sqlalchemy in .\anaconda3\Lib\site-packages (2.0.51)
Collecting sqlalchemy
  Downloading sqlalchemy-2.1.4-cp314-cp314-win_amd64.whl.metadata (9.9 kB)
Collecting langchain-core<2.0.0,>=1.6.9 (from langchain)
  Downloading langchain_core-1.6.9-py3-none-any.whl.metadata (4.8 kB)
Collecting langgraph<1.3.0,>=1.2.11 (from langchain)
  Downloading langgraph-1.2.14-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in .\anaconda3\Lib\site-packages (from langchain) (2.13.4)
Requirement already satisfied: httpx<1.0.0,>=0.23.0 in .\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.9->langchain) (0.28.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in .\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.9->langchain) (1.33)
Collecting langchain-protocol>=0.0.17 (from langchain-core<2.0.0,>=1.6.9->langchain)
  Downloading langchain_protocol-0.0.19-py3-none-any.whl.metadata (2.4 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core<2.0.0,>=1.6.9->langchain)
  Downloading langsmith-0.14.7-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: packaging>=23.2.0 in .\AppData\Roaming\Python\Python314\site-packages (from langchain-core<2.0.0,>=1.6.9->langchain) (26.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in .\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.9->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in .\anaconda3\Lib\site-packages (from langchain-core<2.0.0,>=1.6.9->langchain) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in .\AppData\Roaming\Python\Python314\site-packages (from langchain-core<2.0.0,>=1.6.9->langchain) (4.16.0)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core<2.0.0,>=1.6.9->langchain)
  Downloading uuid_utils-0.17.1-cp314-cp314-win_amd64.whl.metadata (6.5 kB)
Requirement already satisfied: anyio in .\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.9->langchain) (4.12.1)
Requirement already satisfied: certifi in .\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.9->langchain) (2026.6.17)
Requirement already satisfied: httpcore==1.* in .\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.9->langchain) (1.0.9)
Requirement already satisfied: idna in .\anaconda3\Lib\site-packages (from httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.9->langchain) (3.18)
Requirement already satisfied: h11>=0.16 in .\anaconda3\Lib\site-packages (from httpcore==1.*->httpx<1.0.0,>=0.23.0->langchain-core<2.0.0,>=1.6.9->langchain) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in .\anaconda3\Lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.6.9->langchain) (3.1.1)
Collecting langgraph-checkpoint<5.0.0,>=4.1.0 (from langgraph<1.3.0,>=1.2.11->langchain)
  Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl.metadata (6.7 kB)
Collecting langgraph-prebuilt<1.2.0,>=1.1.0 (from langgraph<1.3.0,>=1.2.11->langchain)
  Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl.metadata (5.2 kB)
Collecting langgraph-sdk<0.5.0,>=0.4.6 (from langgraph<1.3.0,>=1.2.11->langchain)
  Downloading langgraph_sdk-0.4.6-py3-none-any.whl.metadata (5.1 kB)
Collecting xxhash>=3.5.0 (from langgraph<1.3.0,>=1.2.11->langchain)
  Downloading xxhash-4.0.1-cp314-cp314-win_amd64.whl.metadata (18 kB)
Collecting ormsgpack>=1.12.0 (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.11->langchain)
  Downloading ormsgpack-1.12.2-cp314-cp314-win_amd64.whl.metadata (3.3 kB)
Collecting orjson>=3.11.5 (from langgraph-sdk<0.5.0,>=0.4.6->langgraph<1.3.0,>=1.2.11->langchain)
  Downloading orjson-3.13.0-cp314-cp314-win_amd64.whl.metadata (43 kB)
Requirement already satisfied: websockets<17,>=14 in .\anaconda3\Lib\site-packages (from langgraph-sdk<0.5.0,>=0.4.6->langgraph<1.3.0,>=1.2.11->langchain) (16.0)
Requirement already satisfied: distro>=1.7.0 in .\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.9->langchain) (1.9.0)
Collecting httpx2<3,>=2 (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.9->langchain)
  Downloading httpx2-2.13.1-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: requests-toolbelt>=1.0.0 in .\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.9->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in .\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.9->langchain) (2.34.2)
Collecting sniffio>=1.1 (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.9->langchain)
  Downloading sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: zstandard>=0.23.0 in .\anaconda3\Lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.9->langchain) (0.25.0)
Collecting httpcore2==2.13.1 (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.9->langchain)
  Downloading httpcore2-2.13.1-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: truststore>=0.10 in .\anaconda3\Lib\site-packages (from httpx2<3,>=2->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.9->langchain) (0.10.4)
Requirement already satisfied: annotated-types>=0.6.0 in .\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in .\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in .\anaconda3\Lib\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in .\anaconda3\Lib\site-packages (from langchain-community) (3.14.1)
Collecting httpx-sse<1.0.0,>=0.4.0 (from langchain-community)
  Downloading httpx_sse-0.4.3-py3-none-any.whl.metadata (9.7 kB)
Collecting langchain-classic<2.0.0,>=1.0.7 (from langchain-community)
  Downloading langchain_classic-1.0.8-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=2.1.0 in .\AppData\Roaming\Python\Python314\site-packages (from langchain-community) (2.5.3)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in .\anaconda3\Lib\site-packages (from langchain-community) (2.14.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in .\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in .\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in .\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in .\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in .\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in .\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in .\anaconda3\Lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.2)
Collecting langchain-text-splitters<2.0.0,>=1.1.2 (from langchain-classic<2.0.0,>=1.0.7->langchain-community)
  Downloading langchain_text_splitters-1.1.3-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: python-dotenv>=0.21.0 in .\anaconda3\Lib\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: charset_normalizer<4,>=2 in .\anaconda3\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.9->langchain) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in .\anaconda3\Lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.6.9->langchain) (2.7.0)
Collecting ollama<1.0.0,>=0.6.1 (from langchain-ollama)
  Downloading ollama-0.6.3-py3-none-any.whl.metadata (7.6 kB)
Downloading langchain-1.4.4-py3-none-any.whl (165 kB)
Downloading langchain_core-1.6.9-py3-none-any.whl (572 kB)
   ---------------------------------------- 0.0/573.0 kB ? eta -:--:--
   ------------------------------------ --- 524.3/573.0 kB 3.8 MB/s eta 0:00:01
   ---------------------------------------- 573.0/573.0 kB 1.8 MB/s  0:00:00
Downloading langgraph-1.2.14-py3-none-any.whl (255 kB)
Downloading langgraph_checkpoint-4.2.0-py3-none-any.whl (56 kB)
Downloading langgraph_prebuilt-1.1.0-py3-none-any.whl (41 kB)
Downloading langgraph_sdk-0.4.6-py3-none-any.whl (162 kB)
Downloading langsmith-0.14.7-py3-none-any.whl (861 kB)
   ---------------------------------------- 0.0/862.0 kB ? eta -:--:--
   ------------ --------------------------- 262.1/862.0 kB ? eta -:--:--
   ---------------------------------------- 862.0/862.0 kB 2.3 MB/s  0:00:00
Downloading httpx2-2.13.1-py3-none-any.whl (95 kB)
Downloading httpcore2-2.13.1-py3-none-any.whl (83 kB)
Downloading uuid_utils-0.17.1-cp314-cp314-win_amd64.whl (177 kB)
Downloading langchain_community-0.4.2-py3-none-any.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   -------- ------------------------------- 0.5/2.4 MB 1.6 MB/s eta 0:00:02
   ----------------- ---------------------- 1.0/2.4 MB 1.7 MB/s eta 0:00:01
   ---------------------- ----------------- 1.3/2.4 MB 1.7 MB/s eta 0:00:01
   ------------------------------- -------- 1.8/2.4 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 2.1/2.4 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 1.7 MB/s  0:00:01
Downloading sqlalchemy-2.1.4-cp314-cp314-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---- ----------------------------------- 0.3/2.4 MB ? eta -:--:--
   ------------ --------------------------- 0.8/2.4 MB 2.2 MB/s eta 0:00:01
   --------------------- ------------------ 1.3/2.4 MB 2.3 MB/s eta 0:00:01
   ------------------------------ --------- 1.8/2.4 MB 2.2 MB/s eta 0:00:01
   ---------------------------------- ----- 2.1/2.4 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 2.1 MB/s  0:00:01
Downloading httpx_sse-0.4.3-py3-none-any.whl (9.0 kB)
Downloading langchain_classic-1.0.8-py3-none-any.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.3/1.0 MB ? eta -:--:--
   ------------------------------ --------- 0.8/1.0 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 1.0/1.0 MB 2.1 MB/s  0:00:00
Downloading langchain_text_splitters-1.1.3-py3-none-any.whl (38 kB)
Downloading langchain_ollama-1.1.0-py3-none-any.whl (31 kB)
Downloading ollama-0.6.3-py3-none-any.whl (16 kB)
Downloading langchain_protocol-0.0.19-py3-none-any.whl (7.3 kB)
Downloading orjson-3.13.0-cp314-cp314-win_amd64.whl (121 kB)
Downloading ormsgpack-1.12.2-cp314-cp314-win_amd64.whl (117 kB)
Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Downloading xxhash-4.0.1-cp314-cp314-win_amd64.whl (37 kB)
Installing collected packages: xxhash, uuid-utils, sqlalchemy, sniffio, ormsgpack, orjson, langchain-protocol, httpx-sse, httpcore2, httpx2, ollama, langsmith, langchain-core, langgraph-sdk, langgraph-checkpoint, langchain-text-splitters, langchain-ollama, langgraph-prebuilt, langchain-classic, langgraph, langchain-community, langchain

  Attempting uninstall: sqlalchemy

    Found existing installation: SQLAlchemy 2.0.51

   --- ------------------------------------  2/22 [sqlalchemy]
    Uninstalling SQLAlchemy-2.0.51:
   --- ------------------------------------  2/22 [sqlalchemy]
      Successfully uninstalled SQLAlchemy-2.0.51
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   --- ------------------------------------  2/22 [sqlalchemy]
   ---------- -----------------------------  6/22 [langchain-protocol]
   -------------- -------------------------  8/22 [httpcore2]
   ---------------- -----------------------  9/22 [httpx2]
   ---------------- -----------------------  9/22 [httpx2]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   -------------------- ------------------- 11/22 [langsmith]
   --------------------- ------------------ 12/22 [langchain-core]
   --------------------- ------------------ 12/22 [langchain-core]
   --------------------- ------------------ 12/22 [langchain-core]
   --------------------- ------------------ 12/22 [langchain-core]
   --------------------- ------------------ 12/22 [langchain-core]
   --------------------- ------------------ 12/22 [langchain-core]
   --------------------- ------------------ 12/22 [langchain-core]
   --------------------- ------------------ 12/22 [langchain-core]
   --------------------- ------------------ 12/22 [langchain-core]
   ----------------------- ---------------- 13/22 [langgraph-sdk]
   ----------------------- ---------------- 13/22 [langgraph-sdk]
   ------------------------- -------------- 14/22 [langgraph-checkpoint]
   ----------------------------- ---------- 16/22 [langchain-ollama]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   -------------------------------- ------- 18/22 [langchain-classic]
   ---------------------------------- ----- 19/22 [langgraph]
   ---------------------------------- ----- 19/22 [langgraph]
   ---------------------------------- ----- 19/22 [langgraph]
   ---------------------------------- ----- 19/22 [langgraph]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]
   ------------------------------------ --- 20/22 [langchain-community]

In [10]:
#Reconnect to your SQLite database
import sqlite3
import pandas as pd
from pathlib import Path

db_path = Path.cwd() / "amazon_sales.db"

print("Database exists:", db_path.exists())
print("Database path:", db_path)

conn = sqlite3.connect(str(db_path))

print(
    "Rows in database:",
    conn.execute("SELECT COUNT(*) FROM amazon_sales").fetchone()[0]
)

Database exists: True
Database path: C:\Users\jayachandran\amazon_sales.db
Rows in database: 128969

In [11]:
#Testing ollama from jupyter
from langchain_ollama import ChatOllama

llm = ChatOllama(
    model="qwen2.5:3b",
    temperature=0
)

response = llm.invoke(
    "Explain SQL GROUP BY in two simple sentences."
)

print(response.content)

SQL GROUP BY is used to group rows that have the same values into aggregates, allowing you to perform calculations on these groups.

In [12]:
#Connecting Langchain to SQLite
from langchain_community.utilities import SQLDatabase

db = SQLDatabase.from_uri(
    "sqlite:///C:/Users/jayachandran/amazon_sales.db",
    include_tables=["amazon_sales"]
)

print("Database connected:", db.dialect)
print("\nAvailable tables:", db.get_usable_table_names())
print("\nTable schema:")
print(db.get_table_info())

C:\Users\jayachandran\AppData\Local\Temp\ipykernel_22228\1683983554.py:2: DeprecationWarning: `langchain-community` is being sunset and is no longer actively maintained. See https://github.com/langchain-ai/langchain-community/issues/674 for details and migration guidance toward standalone integration packages.
  from langchain_community.utilities import SQLDatabase

Database connected: sqlite

Available tables: ['amazon_sales']

Table schema:

CREATE TABLE amazon_sales (
	order_id TEXT,
	date TIMESTAMP,
	status TEXT,
	fulfilment TEXT,
	sales_channel TEXT,
	ship_service_level TEXT,
	style TEXT,
	sku TEXT,
	category TEXT,
	size TEXT,
	asin TEXT,
	courier_status TEXT,
	qty INTEGER,
	currency TEXT,
	order_value REAL,
	ship_city TEXT,
	ship_state TEXT,
	ship_postal_code REAL,
	ship_country TEXT,
	promotion_ids TEXT,
	b2b INTEGER,
	fulfilled_by TEXT
)

/*
3 rows from amazon_sales table:
order_id	date	status	fulfilment	sales_channel	ship_service_level	style	sku	category	size	asin	courier_status	qty	currency	order_value	ship_city	ship_state	ship_postal_code	ship_country	promotion_ids	b2b	fulfilled_by
405-8078784-5731545	2022-04-30 00:00:00	Cancelled	Merchant	Amazon.in	Standard	SET389	SET389-KR-NP-S	Set	S	B09KXVBD7Z	None	0	INR	647.62	MUMBAI	MAHARASHTRA	400081.0	IN	None	0	Easy Ship
171-9198151-1101146	2022-04-30 00:00:00	Shipped - Delivered to Buyer	Merchant	Amazon.in	Standard	JNE3781	JNE3781-KR-XXXL	kurta	3XL	B09K3WFS32	Shipped	1	INR	406.0	BENGALURU	KARNATAKA	560085.0	IN	Amazon PLCC Free-Financing Universal Merchant AAT-WNKTBO3K27EJC,Amazon PLCC Free-Financing Universal	0	Easy Ship
404-0687676-7273146	2022-04-30 00:00:00	Shipped	Amazon	Amazon.in	Expedited	JNE3371	JNE3371-KR-XL	kurta	XL	B07WV4JV4D	Shipped	1	INR	329.0	NAVI MUMBAI	MAHARASHTRA	410210.0	IN	IN Core Free Shipping 2015/04/08 23-48-5-108	1	None
*/

In [41]:
#Generating SQL from a natural-language question
from langchain_core.prompts import ChatPromptTemplate

sql_prompt = ChatPromptTemplate.from_template("""
You are a SQL expert working with a SQLite database.

Table schema:
{schema}

Convert the user's question into one SQLite SELECT query.

Rules:
- Use only tables and columns in the schema.
- Generate read-only SELECT queries only.
- Do not use INSERT, UPDATE, DELETE, DROP, ALTER, or other modifications.
- Return only the SQL query, without Markdown fences.
- Use exact column values and the provided schema.
- Do not invent filters that the user did not request.
- Use LIMIT when the user requests a specific number of results.
- Never invent filters or assume state names use country-code prefixes.
- Do not exclude cancelled orders unless the user requests it.
- If a query returns no rows, clearly report that no matching data was found.
- For conditional counts, use SUM(CASE WHEN condition THEN 1 ELSE 0 END).
- Never use ELSE 1 when counting only matching records.
- For percentages, divide the matching record count by the total record count.
- Do not filter out records needed for the denominator.
- Check that cancellation percentages cannot exceed 100%.
- When the user requests results for each group, do not filter out groups using WHERE.
- When calculating percentages by group, calculate the numerator and denominator within each group.
- Do not add filters for values that are already represented by GROUP BY.
- For cancellation percentages, always use 100.0 rather than 100 to preserve decimal precision.
- When calculating a percentage for each group, include all records in that group.
- Do not add a WHERE clause to filter groups when the user requests results for each group.
- Do not filter out values that are already handled by GROUP BY.
- Calculate the percentage as 100.0 * SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) / COUNT(*).
- Never use ELSE 1 when counting only matching records.


Question: {question}
""")

question = "Which 10 product categories have the highest total order value?"

prompt_value = sql_prompt.invoke({
    "schema": db.get_table_info(),
    "question": question
})

response = llm.invoke(prompt_value)

print(response.content)

SELECT category, SUM(order_value) AS total_order_value
FROM amazon_sales
GROUP BY category
ORDER BY total_order_value DESC
LIMIT 10

In [14]:
#validate and execute the generated SQL
import re
import pandas as pd

def run_safe_sql(sql):
    # Remove optional Markdown fences
    sql = sql.strip()
    sql = re.sub(r"^```(?:sql)?\s*|\s*```$", "", sql,
                 flags=re.IGNORECASE).strip()

    # Allow one SELECT query only
    if not re.match(r"^SELECT\b", sql, re.IGNORECASE):
        raise ValueError("Only SELECT queries are allowed.")

    # Reject multiple statements
    if ";" in sql.rstrip(";"):
        raise ValueError("Only one SQL statement is allowed.")

    # Block comments and common unsafe keywords
    if re.search(r"--|/\*|\*/", sql):
        raise ValueError("SQL comments are not allowed.")

    if re.search(
        r"\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|REPLACE|"
        r"ATTACH|DETACH|PRAGMA|VACUUM|INTO|UNION)\b",
        sql,
        re.IGNORECASE
    ):
        raise ValueError("Unsafe SQL pattern detected.")

    # Require the approved table
    if not re.search(r"\bFROM\s+amazon_sales\b", sql, re.IGNORECASE):
        raise ValueError("Query must use amazon_sales.")

    # Enforce a maximum result size
    if not re.search(r"\bLIMIT\s+\d+\b", sql, re.IGNORECASE):
        sql = sql.rstrip(";") + " LIMIT 100"

    # Open SQLite in read-only mode
    from pathlib import Path
    from urllib.parse import quote

    db_uri = (
        "file:" + quote(str(db_path.resolve()).replace("\\", "/"),
                        safe="/:") + "?mode=ro"
    )

    with sqlite3.connect(db_uri, uri=True) as read_conn:
        read_conn.execute("PRAGMA query_only = ON")
        return pd.read_sql_query(sql, read_conn)

In [15]:
#Execute the generated query
# Use the SQL generated in Step 14
generated_sql = response.content

# Execute only after validation
result = run_safe_sql(generated_sql)

display(result)

        category  total_order_value
0            Set        39202022.03
1          kurta        21299013.70
2  Western Dress        11216072.69
3            Top         5347792.30
4   Ethnic Dress          791217.66
5         Blouse          458408.18
6         Bottom          150667.98
7          Saree          123933.76
8        Dupatta             915.00

In [16]:
#Make the assistant answer different questions
def ask_sql_assistant(question):
    # Generate SQL from the user's question
    prompt_value = sql_prompt.invoke({
        "schema": db.get_table_info(),
        "question": question
    })

    response = llm.invoke(prompt_value)
    generated_sql = response.content.strip()

    print("Generated SQL:")
    print(generated_sql)

    # Validate and execute safely
    result = run_safe_sql(generated_sql)

    print("\nQuery results:")
    display(result)

    return result

In [17]:
ask_sql_assistant(
    "Which 10 Indian states have the highest total recorded order value?"
)

Generated SQL:
SELECT ship_state, SUM(order_value) AS total_order_value
FROM amazon_sales
WHERE ship_state LIKE 'IN%'
GROUP BY ship_state
ORDER BY total_order_value DESC
LIMIT 10

Query results:

Empty DataFrame
Columns: [ship_state, total_order_value]
Index: []

Empty DataFrame
Columns: [ship_state, total_order_value]
Index: []

In [18]:
ask_sql_assistant("How many orders are there for each order status")

Generated SQL:
SELECT status, COUNT(*) AS order_count FROM amazon_sales GROUP BY status

Query results:

                           status  order_count
0                       Cancelled        18329
1                         Pending          658
2   Pending - Waiting for Pick Up          281
3                         Shipped        77801
4               Shipped - Damaged            1
5    Shipped - Delivered to Buyer        28769
6       Shipped - Lost in Transit            5
7      Shipped - Out for Delivery           35
8             Shipped - Picked Up          973
9     Shipped - Rejected by Buyer           11
10   Shipped - Returned to Seller         1953
11  Shipped - Returning to Seller          145
12                       Shipping            8

                           status  order_count
0                       Cancelled        18329
1                         Pending          658
2   Pending - Waiting for Pick Up          281
3                         Shipped        77801
4               Shipped - Damaged            1
5    Shipped - Delivered to Buyer        28769
6       Shipped - Lost in Transit            5
7      Shipped - Out for Delivery           35
8             Shipped - Picked Up          973
9     Shipped - Rejected by Buyer           11
10   Shipped - Returned to Seller         1953
11  Shipped - Returning to Seller          145
12                       Shipping            8

In [19]:
#Improve SQL generation accuracy
#Test a corrected question
ask_sql_assistant(
    "Which 10 states have the highest total recorded order value? "
    "Use ship_state, group by state, sum order_value, "
    "sort descending, and return only 10 rows. "
    "Do not filter states using country codes or prefixes."
)

Generated SQL:
SELECT ship_state, SUM(order_value) AS total_order_value
FROM amazon_sales
GROUP BY ship_state
ORDER BY total_order_value DESC
LIMIT 10

Query results:

       ship_state  total_order_value
0     MAHARASHTRA        13334595.14
1       KARNATAKA        10481114.37
2       TELANGANA         6916615.65
3   UTTAR PRADESH         6816109.08
4      TAMIL NADU         6515650.11
5           DELHI         4235215.97
6          KERALA         3830227.58
7     WEST BENGAL         3507880.44
8  ANDHRA PRADESH         3219831.72
9         HARYANA         2882092.99

       ship_state  total_order_value
0     MAHARASHTRA        13334595.14
1       KARNATAKA        10481114.37
2       TELANGANA         6916615.65
3   UTTAR PRADESH         6816109.08
4      TAMIL NADU         6515650.11
5           DELHI         4235215.97
6          KERALA         3830227.58
7     WEST BENGAL         3507880.44
8  ANDHRA PRADESH         3219831.72
9         HARYANA         2882092.99

In [22]:
ask_sql_assistant(
    "What is the total recorded order value for cancelled orders?"
)

Generated SQL:
SELECT SUM(order_value) AS total_order_value FROM amazon_sales WHERE status = 'Cancelled'

Query results:

   total_order_value
0          6919284.3

   total_order_value
0          6919284.3

In [23]:
ask_sql_assistant(
    "What is the total recorded order value for each month? "
    "Group the results by year and month, and sort chronologically."
)

Generated SQL:
SELECT strftime('%Y-%m', date), SUM(order_value) AS total_order_value
FROM amazon_sales
GROUP BY strftime('%Y-%m', date)
ORDER BY date

Query results:

  strftime('%Y-%m', date)  total_order_value
0                 2022-03          101683.85
1                 2022-04        28838708.32
2                 2022-05        26225004.75
3                 2022-06        23424646.38

  strftime('%Y-%m', date)  total_order_value
0                 2022-03          101683.85
1                 2022-04        28838708.32
2                 2022-05        26225004.75
3                 2022-06        23424646.38

In [24]:
#Test sales performance by fulfilment method
ask_sql_assistant(
    "What is the total recorded order value and number of records "
    "for each fulfilment method? "
    "Group by fulfilment and sort by total order value descending."
)

Generated SQL:
SELECT fulfilment, SUM(order_value) AS total_order_value, COUNT(*) AS record_count
FROM amazon_sales
GROUP BY fulfilment
ORDER BY total_order_value DESC

Query results:

  fulfilment  total_order_value  record_count
0     Amazon         54319516.0         89692
1   Merchant         24270527.3         39277

  fulfilment  total_order_value  record_count
0     Amazon         54319516.0         89692
1   Merchant         24270527.3         39277

In [26]:
#Analyse order status and fulfilment together
ask_sql_assistant(
    "How many records are there for each combination of "
    "fulfilment method and order status? "
    "Group by fulfilment and status, and sort by record count descending."
)

Generated SQL:
SELECT fulfilment, status, COUNT(*) AS record_count
FROM amazon_sales
GROUP BY fulfilment, status
ORDER BY record_count DESC

Query results:

   fulfilment                         status  record_count
0      Amazon                        Shipped         77801
1    Merchant   Shipped - Delivered to Buyer         28769
2      Amazon                      Cancelled         11468
3    Merchant                      Cancelled          6861
4    Merchant   Shipped - Returned to Seller          1953
5    Merchant            Shipped - Picked Up           973
6      Amazon                        Pending           415
7    Merchant  Pending - Waiting for Pick Up           281
8    Merchant                        Pending           243
9    Merchant  Shipped - Returning to Seller           145
10   Merchant     Shipped - Out for Delivery            35
11   Merchant    Shipped - Rejected by Buyer            11
12     Amazon                       Shipping             8
13   Merchant      Shipped - Lost in Transit             5
14   Merchant              Shipped - Damaged             1

   fulfilment                         status  record_count
0      Amazon                        Shipped         77801
1    Merchant   Shipped - Delivered to Buyer         28769
2      Amazon                      Cancelled         11468
3    Merchant                      Cancelled          6861
4    Merchant   Shipped - Returned to Seller          1953
5    Merchant            Shipped - Picked Up           973
6      Amazon                        Pending           415
7    Merchant  Pending - Waiting for Pick Up           281
8    Merchant                        Pending           243
9    Merchant  Shipped - Returning to Seller           145
10   Merchant     Shipped - Out for Delivery            35
11   Merchant    Shipped - Rejected by Buyer            11
12     Amazon                       Shipping             8
13   Merchant      Shipped - Lost in Transit             5
14   Merchant              Shipped - Damaged             1

In [27]:
#Calculate the cancellation rate
ask_sql_assistant(
    "What percentage of all records have status Cancelled? "
    "Return the total number of records, the number of cancelled "
    "records, and the cancellation percentage. "
    "Use 100.0 times the cancelled record count divided by "
    "the total record count")

Generated SQL:
SELECT
    COUNT(*) AS total_records,
    SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled_records,
    CAST(100.0 * SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) AS REAL) / COUNT(*) AS cancellation_percentage
FROM amazon_sales
WHERE status = 'Cancelled'

Query results:

   total_records  cancelled_records  cancellation_percentage
0          18329              18329                    100.0

   total_records  cancelled_records  cancellation_percentage
0          18329              18329                    100.0

In [28]:
#Correct the cancellation rate calculation
ask_sql_assistant(
    "Calculate the cancellation percentage across the entire "
    "amazon_sales table. Return total_records, cancelled_records, "
    "and cancellation_percentage. Do not use a WHERE clause. "
    "Use COUNT(*) for total_records and "
    "SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) "
    "for cancelled_records. Calculate the percentage as "
    "100.0 * cancelled_records / total_records."
)

Generated SQL:
SELECT
    COUNT(*) AS total_records,
    SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled_records,
    CAST(100.0 * SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) AS REAL) / COUNT(*) AS cancellation_percentage
FROM amazon_sales

Query results:

   total_records  cancelled_records  cancellation_percentage
0         128969              18329                14.211942

   total_records  cancelled_records  cancellation_percentage
0         128969              18329                14.211942

In [29]:
#Compare cancellation rates by fulfilment method
ask_sql_assistant(
    "For each fulfilment method, calculate the total number "
    "of records, the number of cancelled records, and the "
    "cancellation percentage within that fulfilment method. "
    "Use conditional aggregation with SUM(CASE WHEN status = "
    "'Cancelled' THEN 1 ELSE 0 END). "
    "Calculate the percentage using 100.0 times cancelled "
    "records divided by total records in each group. "
    "Group by fulfilment and sort by cancellation percentage "
    "descending. Do not filter rows using WHERE."
)

Generated SQL:
SELECT
    fulfilment,
    COUNT(*) AS total_records,
    SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled_records,
    CAST(SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) AS REAL) * 100.0 / COUNT(*) AS cancellation_percentage
FROM amazon_sales
GROUP BY fulfilment
ORDER BY cancellation_percentage DESC

Query results:

  fulfilment  total_records  cancelled_records  cancellation_percentage
0   Merchant          39277               6861                17.468238
1     Amazon          89692              11468                12.785979

  fulfilment  total_records  cancelled_records  cancellation_percentage
0   Merchant          39277               6861                17.468238
1     Amazon          89692              11468                12.785979

In [30]:
#Find the top 10 cities by order value
ask_sql_assistant(
    "Which 10 shipping cities have the highest total recorded "
    "order value? Use ship_city and SUM(order_value), group by "
    "ship_city, sort by total order value descending, and return "
    "only 10 cities. Do not filter out any order statuses."
)

Generated SQL:
SELECT ship_city, SUM(order_value) AS total_order_value
FROM amazon_sales
GROUP BY ship_city
ORDER BY total_order_value DESC
LIMIT 10

Query results:

   ship_city  total_order_value
0  BENGALURU         6849664.99
1  HYDERABAD         4946032.82
2     MUMBAI         3704461.80
3  NEW DELHI         3613874.78
4    CHENNAI         3098745.74
5       PUNE         2337579.18
6    KOLKATA         1414978.87
7   GURUGRAM         1221618.74
8      THANE         1004355.29
9    LUCKNOW          933926.34

   ship_city  total_order_value
0  BENGALURU         6849664.99
1  HYDERABAD         4946032.82
2     MUMBAI         3704461.80
3  NEW DELHI         3613874.78
4    CHENNAI         3098745.74
5       PUNE         2337579.18
6    KOLKATA         1414978.87
7   GURUGRAM         1221618.74
8      THANE         1004355.29
9    LUCKNOW          933926.34

In [32]:
#Find the best-selling product categories by fulfilment method
ask_sql_assistant(
    "For each combination of product category and fulfilment "
    "method, calculate the total recorded order value and "
    "number of records. Group by category and fulfilment, "
    "sort by total recorded order value descending, and "
    "return the top 10 combinations. Do not filter by order status."
)

Generated SQL:
SELECT fulfilment, category, SUM(order_value) AS total_order_value, COUNT(*) AS record_count
FROM amazon_sales
GROUP BY fulfilment, category
ORDER BY total_order_value DESC
LIMIT 10

Query results:

  fulfilment       category  total_order_value  record_count
0     Amazon            Set        27634853.00         35545
1     Amazon          kurta        15169235.00         35621
2   Merchant            Set        11567169.03         14736
3     Amazon  Western Dress         6273319.00          8531
4   Merchant          kurta         6129778.70         14253
5   Merchant  Western Dress         4942753.69          6969
6     Amazon            Top         4133343.00          8072
7   Merchant            Top         1214449.30          2550
8     Amazon   Ethnic Dress          581747.00           848
9     Amazon         Blouse          341361.00           692

  fulfilment       category  total_order_value  record_count
0     Amazon            Set        27634853.00         35545
1     Amazon          kurta        15169235.00         35621
2   Merchant            Set        11567169.03         14736
3     Amazon  Western Dress         6273319.00          8531
4   Merchant          kurta         6129778.70         14253
5   Merchant  Western Dress         4942753.69          6969
6     Amazon            Top         4133343.00          8072
7   Merchant            Top         1214449.30          2550
8     Amazon   Ethnic Dress          581747.00           848
9     Amazon         Blouse          341361.00           692

In [33]:
#Test whether your AI can compare average order value
ask_sql_assistant(
    "Which 10 product categories have the highest average "
    "recorded order value per record? Calculate AVG(order_value) "
    "and COUNT(*) for each category. Group by category, "
    "sort by average order value descending, and return "
    "only 10 rows. Do not filter by order status."
)

Generated SQL:
SELECT category, AVG(order_value) AS avg_order_value, COUNT(*) AS count_records
FROM amazon_sales
GROUP BY category
ORDER BY AVG(order_value) DESC
LIMIT 10

Query results:

        category  avg_order_value  count_records
0            Set       833.376319          50281
1          Saree       799.572645            164
2  Western Dress       762.790580          15500
3   Ethnic Dress       723.895389           1159
4            Top       526.098603          10622
5         Blouse       520.327106            926
6          kurta       455.925458          49874
7         Bottom       358.733286            440
8        Dupatta       305.000000              3

        category  avg_order_value  count_records
0            Set       833.376319          50281
1          Saree       799.572645            164
2  Western Dress       762.790580          15500
3   Ethnic Dress       723.895389           1159
4            Top       526.098603          10622
5         Blouse       520.327106            926
6          kurta       455.925458          49874
7         Bottom       358.733286            440
8        Dupatta       305.000000              3

In [34]:
#Compare cancellation rates by product category
ask_sql_assistant(
    "Calculate the cancellation rate for each product category. "
    "Return category, total_records, cancelled_records, "
    "and cancellation_percentage. Use all records in the "
    "denominator and count records where status equals "
    "'Cancelled' in the numerator. Calculate the percentage "
    "as 100.0 times cancelled_records divided by total_records. "
    "Group by category and sort by cancellation_percentage "
    "descending. Do not use a WHERE clause."
)

Generated SQL:
SELECT category, COUNT(*) AS total_records, SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled_records, CAST(SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) AS REAL) * 100.0 / COUNT(*) AS cancellation_percentage
FROM amazon_sales
GROUP BY category
ORDER BY cancellation_percentage DESC

Query results:

        category  total_records  cancelled_records  cancellation_percentage
0            Set          50281               7336                14.590004
1          kurta          49874               7253                14.542647
2  Western Dress          15500               2122                13.690323
3         Bottom            440                 60                13.636364
4          Saree            164                 21                12.804878
5         Blouse            926                116                12.526998
6   Ethnic Dress           1159                145                12.510785
7            Top          10622               1276                12.012804
8        Dupatta              3                  0                 0.000000

        category  total_records  cancelled_records  cancellation_percentage
0            Set          50281               7336                14.590004
1          kurta          49874               7253                14.542647
2  Western Dress          15500               2122                13.690323
3         Bottom            440                 60                13.636364
4          Saree            164                 21                12.804878
5         Blouse            926                116                12.526998
6   Ethnic Dress           1159                145                12.510785
7            Top          10622               1276                12.012804
8        Dupatta              3                  0                 0.000000

In [35]:
#Compare cancellation rates by fulfilment method
ask_sql_assistant(
    "Calculate the cancellation rate separately for each "
    "fulfilment method. Return fulfilment, total_records, "
    "cancelled_records, and cancellation_percentage. "
    "Count all records in the denominator and count records "
    "with status equal to 'Cancelled' in the numerator. "
    "Calculate cancellation_percentage as 100.0 times "
    "cancelled_records divided by total_records. "
    "Group by fulfilment, sort by cancellation_percentage "
    "descending, and do not use a WHERE clause."
)

Generated SQL:
SELECT fulfilment, COUNT(*) AS total_records, SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled_records, CAST(COUNT(*) AS REAL) * 100.0 / SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 1 END) AS cancellation_percentage
FROM amazon_sales
GROUP BY fulfilment
ORDER BY cancellation_percentage DESC

Query results:

  fulfilment  total_records  cancelled_records  cancellation_percentage
0   Merchant          39277               6861                    100.0
1     Amazon          89692              11468                    100.0

  fulfilment  total_records  cancelled_records  cancellation_percentage
0   Merchant          39277               6861                    100.0
1     Amazon          89692              11468                    100.0

In [36]:

#Correct cancellation rate by fulfilment

corrected_sql = """
SELECT
    fulfilment,
    COUNT(*) AS total_records,
    SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END)
        AS cancelled_records,
    100.0 * SUM(
        CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END
    ) / COUNT(*) AS cancellation_percentage
FROM amazon_sales
GROUP BY fulfilment
ORDER BY cancellation_percentage DESC;
"""

result = run_safe_sql(corrected_sql)
display(result)

  fulfilment  total_records  cancelled_records  cancellation_percentage
0   Merchant          39277               6861                17.468238
1     Amazon          89692              11468                12.785979

In [42]:
#Retest cancellation rate by fulfilment

ask_sql_assistant(
    "Calculate cancellation percentage for each fulfilment method. "
    "Return fulfilment, total_records, cancelled_records, "
    "and cancellation_percentage. Count all records in the "
    "denominator and only records with status = 'Cancelled' "
    "in the numerator. Use SUM(CASE WHEN status = 'Cancelled' "
    "THEN 1 ELSE 0 END) and divide by COUNT(*). "
    "Group by fulfilment and sort by cancellation percentage "
    "descending. Do not use a WHERE clause."
)

Generated SQL:
SELECT fulfilment, COUNT(*) AS total_records, SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled_records, 100.0 * SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) / COUNT(*) AS cancellation_percentage
FROM amazon_sales
GROUP BY fulfilment
ORDER BY cancellation_percentage DESC

Query results:

  fulfilment  total_records  cancelled_records  cancellation_percentage
0   Merchant          39277               6861                17.468238
1     Amazon          89692              11468                12.785979

  fulfilment  total_records  cancelled_records  cancellation_percentage
0   Merchant          39277               6861                17.468238
1     Amazon          89692              11468                12.785979

In [43]:
#Test whether the assistant works reliably
ask_sql_assistant(
    "For each order status, return the total number of records. "
    "Sort by record count descending. Include all statuses."
)

Generated SQL:
SELECT status, COUNT(*) AS record_count
FROM amazon_sales
GROUP BY status
ORDER BY record_count DESC

Query results:

                           status  record_count
0                         Shipped         77801
1    Shipped - Delivered to Buyer         28769
2                       Cancelled         18329
3    Shipped - Returned to Seller          1953
4             Shipped - Picked Up           973
5                         Pending           658
6   Pending - Waiting for Pick Up           281
7   Shipped - Returning to Seller           145
8      Shipped - Out for Delivery            35
9     Shipped - Rejected by Buyer            11
10                       Shipping             8
11      Shipped - Lost in Transit             5
12              Shipped - Damaged             1

                           status  record_count
0                         Shipped         77801
1    Shipped - Delivered to Buyer         28769
2                       Cancelled         18329
3    Shipped - Returned to Seller          1953
4             Shipped - Picked Up           973
5                         Pending           658
6   Pending - Waiting for Pick Up           281
7   Shipped - Returning to Seller           145
8      Shipped - Out for Delivery            35
9     Shipped - Rejected by Buyer            11
10                       Shipping             8
11      Shipped - Lost in Transit             5
12              Shipped - Damaged             1

In [44]:
#Check revenue by category
ask_sql_assistant(
    "For each product category, calculate total order value "
    "and the number of records. Include all categories and "
    "sort by total order value from highest to lowest."
)

Generated SQL:
SELECT category, SUM(order_value) AS total_order_value, COUNT(*) AS record_count
FROM amazon_sales
GROUP BY category
ORDER BY total_order_value DESC

Query results:

        category  total_order_value  record_count
0            Set        39202022.03         50281
1          kurta        21299013.70         49874
2  Western Dress        11216072.69         15500
3            Top         5347792.30         10622
4   Ethnic Dress          791217.66          1159
5         Blouse          458408.18           926
6         Bottom          150667.98           440
7          Saree          123933.76           164
8        Dupatta             915.00             3

        category  total_order_value  record_count
0            Set        39202022.03         50281
1          kurta        21299013.70         49874
2  Western Dress        11216072.69         15500
3            Top         5347792.30         10622
4   Ethnic Dress          791217.66          1159
5         Blouse          458408.18           926
6         Bottom          150667.98           440
7          Saree          123933.76           164
8        Dupatta             915.00             3

In [45]:
#Test date-based analysis
ask_sql_assistant(
    "Calculate the total order value for each month. "
    "Group the results chronologically by year and month. "
    "Return the month and total order value."
)

Generated SQL:
SELECT strftime('%Y-%m', date) AS month, SUM(order_value) AS total_order_value
FROM amazon_sales
GROUP BY month
ORDER BY month

Query results:

     month  total_order_value
0  2022-03          101683.85
1  2022-04        28838708.32
2  2022-05        26225004.75
3  2022-06        23424646.38

     month  total_order_value
0  2022-03          101683.85
1  2022-04        28838708.32
2  2022-05        26225004.75
3  2022-06        23424646.38

In [46]:
#CHeck the dataset's date range
run_safe_sql("""
SELECT
    MIN(date) AS earliest_date,
    MAX(date) AS latest_date,
    COUNT(*) AS total_records,
    COUNT(date) AS records_with_date
FROM amazon_sales;
""")

         earliest_date          latest_date  total_records  records_with_date
0  2022-03-31 00:00:00  2022-06-29 00:00:00         128969             128969

In [47]:
#Verify whether the assistant blocks unsafe SQL commands such as DELETE, DROP and UPDATE
# Test whether unsafe SQL is blocked

unsafe_queries = [
    "DROP TABLE amazon_sales;",
    "DELETE FROM amazon_sales;",
    "UPDATE amazon_sales SET status = 'Cancelled';"
]

for query in unsafe_queries:
    try:
        result = run_safe_sql(query)
        print("CHECK: Review this query's handling:", query)
        print(result)
    except Exception as e:
        print("BLOCKED:", query)
        print("Reason:", e)

BLOCKED: DROP TABLE amazon_sales;
Reason: Only SELECT queries are allowed.
BLOCKED: DELETE FROM amazon_sales;
Reason: Only SELECT queries are allowed.
BLOCKED: UPDATE amazon_sales SET status = 'Cancelled';
Reason: Only SELECT queries are allowed.

In [48]:
# Test SQL injection protection

injection_query = """
SELECT * FROM amazon_sales;
DROP TABLE amazon_sales;
"""

try:
    result = run_safe_sql(injection_query)
    print(result)
except Exception as e:
    print("BLOCKED:", e)

BLOCKED: Only one SQL statement is allowed.

In [49]:
# Test invalid SQL handling

try:
    result = run_safe_sql(
        "SELECT * FROM invalid_table;"
    )
    print(result)
except Exception as e:
    print("ERROR HANDLED:", e)

ERROR HANDLED: Query must use amazon_sales.

In [50]:
# Test that valid queries still work

result = run_safe_sql("""
SELECT status, COUNT(*) AS record_count
FROM amazon_sales
GROUP BY status
ORDER BY record_count DESC;
""")

display(result)

                           status  record_count
0                         Shipped         77801
1    Shipped - Delivered to Buyer         28769
2                       Cancelled         18329
3    Shipped - Returned to Seller          1953
4             Shipped - Picked Up           973
5                         Pending           658
6   Pending - Waiting for Pick Up           281
7   Shipped - Returning to Seller           145
8      Shipped - Out for Delivery            35
9     Shipped - Rejected by Buyer            11
10                       Shipping             8
11      Shipped - Lost in Transit             5
12              Shipped - Damaged             1

In [51]:
# Test empty-result handling

result = run_safe_sql("""
SELECT *
FROM amazon_sales
WHERE status = 'Nonexistent Status';
""")

display(result)

Empty DataFrame
Columns: [order_id, date, status, fulfilment, sales_channel, ship_service_level, style, sku, category, size, asin, courier_status, qty, currency, order_value, ship_city, ship_state, ship_postal_code, ship_country, promotion_ids, b2b, fulfilled_by]
Index: []

[0 rows x 22 columns]

In [52]:
# Verify total records and order value

result = run_safe_sql("""
SELECT
    COUNT(*) AS total_records,
    SUM(order_value) AS total_order_value
FROM amazon_sales;
""")

display(result)

   total_records  total_order_value
0         128969         78590043.3

In [53]:
# Test end-to-end AI SQL assistant

ask_sql_assistant(
    "What are the top 5 product categories by total order value? "
    "Return category and total order value, sorted descending."
)

Generated SQL:
SELECT category, SUM(order_value) AS total_order_value
FROM amazon_sales
GROUP BY category
ORDER BY total_order_value DESC
LIMIT 5

Query results:

        category  total_order_value
0            Set        39202022.03
1          kurta        21299013.70
2  Western Dress        11216072.69
3            Top         5347792.30
4   Ethnic Dress          791217.66

        category  total_order_value
0            Set        39202022.03
1          kurta        21299013.70
2  Western Dress        11216072.69
3            Top         5347792.30
4   Ethnic Dress          791217.66

In [54]:
# Test a combined business analysis question

ask_sql_assistant(
    "For each fulfilment method, show the total number of "
    "records, cancelled records, and cancellation percentage. "
    "Include all records in the denominator, group by fulfilment, "
    "and sort by cancellation percentage from highest to lowest."
)

Generated SQL:
SELECT
    fulfilment,
    COUNT(*) AS total_records,
    SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled_records,
    100.0 * SUM(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) / COUNT(*) AS cancellation_percentage
FROM amazon_sales
GROUP BY fulfilment
ORDER BY cancellation_percentage DESC

Query results:

  fulfilment  total_records  cancelled_records  cancellation_percentage
0   Merchant          39277               6861                17.468238
1     Amazon          89692              11468                12.785979

  fulfilment  total_records  cancelled_records  cancellation_percentage
0   Merchant          39277               6861                17.468238
1     Amazon          89692              11468                12.785979

In [55]:
# Test monthly sales analysis

ask_sql_assistant(
    "Show monthly total order value from the date column. "
    "Return month and total order value, grouped by month "
    "and sorted chronologically."
)

Generated SQL:
SELECT strftime('%Y-%m', date), SUM(order_value) AS total_order_value
FROM amazon_sales
GROUP BY strftime('%Y-%m', date)
ORDER BY date

Query results:

  strftime('%Y-%m', date)  total_order_value
0                 2022-03          101683.85
1                 2022-04        28838708.32
2                 2022-05        26225004.75
3                 2022-06        23424646.38

  strftime('%Y-%m', date)  total_order_value
0                 2022-03          101683.85
1                 2022-04        28838708.32
2                 2022-05        26225004.75
3                 2022-06        23424646.38

In [56]:
# Test top 10 product categories by order value

ask_sql_assistant(
    "Which 10 product categories have the highest total order value? "
    "Calculate SUM(order_value) for each category, sort from highest "
    "to lowest, and return only the top 10."
)

Generated SQL:
SELECT category, SUM(order_value) AS total_order_value
FROM amazon_sales
GROUP BY category
ORDER BY total_order_value DESC
LIMIT 10

Query results:

        category  total_order_value
0            Set        39202022.03
1          kurta        21299013.70
2  Western Dress        11216072.69
3            Top         5347792.30
4   Ethnic Dress          791217.66
5         Blouse          458408.18
6         Bottom          150667.98
7          Saree          123933.76
8        Dupatta             915.00

        category  total_order_value
0            Set        39202022.03
1          kurta        21299013.70
2  Western Dress        11216072.69
3            Top         5347792.30
4   Ethnic Dress          791217.66
5         Blouse          458408.18
6         Bottom          150667.98
7          Saree          123933.76
8        Dupatta             915.00

In [57]:
# Final test: invalid SQL handling
try:
    run_safe_sql("SELECT * FROM invalid_table;")
except Exception as e:
    print("PASS: Error handled safely.")
    print("Message:", e)

PASS: Error handled safely.
Message: Query must use amazon_sales.